import { MarkerType } from "reactflow";

export const initialNodes = [
  {
    id: "dashboard",
    type: "custom",
    position: { x: 400, y: 20 },
    data: {
      label: "MASHome",
      count: "23,386",
      route: "/dashboard",
      icon: "dashboard",
      color: "#475569",
      description: "Total Records",
      size: "large",
    },
  },
  {
    id: "targets",
    type: "custom",
    position: { x: 400, y: 180 },
    data: {
      label: "Targets",
      count: "4,298",
      route: "/targets",
      icon: "target",
      color: "#10B981",
      description: "Therapeutic Targets",
      size: "medium",
    },
  },
  {
    id: "genes",
    type: "custom",
    position: { x: 120, y: 380 },
    data: {
      label: "Genes",
      count: "11,195",
      route: "/genes",
      icon: "dna",
      color: "#3B82F6",
      description: "Gene Information",
      size: "medium",
    },
  },
  {
    id: "drugs",
    type: "custom",
    position: { x: 400, y: 380 },
    data: {
      label: "Drugs",
      count: "4",
      route: "/drugs",
      icon: "pill",
      color: "#8B5CF6",
      description: "Drug Database",
      size: "medium",
    },
  },
  {
    id: "biomarkers",
    type: "custom",
    position: { x: 680, y: 380 },
    data: {
      label: "Biomarkers",
      count: "2,512",
      route: "/biomarkers",
      icon: "activity",
      color: "#F59E0B",
      description: "Biomarker Discovery",
      size: "medium",
    },
  },
  {
    id: "bioactives",
    type: "custom",
    position: { x: 250, y: 580 },
    data: {
      label: "Bioactives",
      count: "786",
      route: "/bioactives",
      icon: "leaf",
      color: "#22C55E",
      description: "Natural Compounds",
      size: "small",
    },
  },
  {
    id: "clinical",
    type: "custom",
    position: { x: 550, y: 580 },
    data: {
      label: "Clinical Trials",
      count: "5,343",
      route: "/clinical-trials",
      icon: "flask",
      color: "#EF4444",
      description: "Clinical Research",
      size: "small",
    },
  },
];

export const initialEdges = [
  {
    id: "1",
    source: "dashboard",
    target: "targets",
    animated: true,
    markerEnd: { type: MarkerType.ArrowClosed },
    style: { stroke: "#94A3B8", strokeWidth: 2 },
  },
  {
    id: "2",
    source: "targets",
    target: "genes",
    animated: true,
    style: { stroke: "#94A3B8", strokeWidth: 2 },
  },
  {
    id: "3",
    source: "targets",
    target: "drugs",
    animated: true,
    style: { stroke: "#94A3B8", strokeWidth: 2 },
  },
  {
    id: "4",
    source: "targets",
    target: "biomarkers",
    animated: true,
    style: { stroke: "#94A3B8", strokeWidth: 2 },
  },
  {
    id: "5",
    source: "drugs",
    target: "bioactives",
    animated: true,
    style: { stroke: "#94A3B8", strokeWidth: 2 },
  },
  {
    id: "6",
    source: "drugs",
    target: "clinical",
    animated: true,
    style: { stroke: "#94A3B8", strokeWidth: 2 },
  },
  {
    id: "7",
    source: "biomarkers",
    target: "bioactives",
    animated: true,
    style: { stroke: "#94A3B8", strokeWidth: 2, strokeDasharray: "5,5" },
  },
  {
    id: "8",
    source: "biomarkers",
    target: "clinical",
    animated: true,
    style: { stroke: "#94A3B8", strokeWidth: 2, strokeDasharray: "5,5" },
  },
];